physical_machine:
  registry:
    addr: 192.168.124.102:5000
  fluentd:
    addr: 192.168.124.102:24224
  workdir: /home/whr/code/communication


virtual_machine:
  workdir: /app
  tmpfs:
    target: /dev/shm
    size: '4g'

  server:
    hostname: pc2
    device: "cuda:0"

  tracker:
    hostname: pc2
  tracker_redis:
    hostname: pc2

  client:
    # # 7
    # - hostname: pc1
    #   num: 1
    #   device: "cuda:0"
    # - hostname: pc2
    #   num: 1
    #   device: "cuda:0"
    # - hostname: pc3
    #   num: 1
    #   device: "cuda:0"
    # - hostname: pc4
    #   num: 1
    #   device: "cuda:0"
    # - hostname: pc5
    #   num: 1
    #   device: "cuda:0"
    # - hostname: pc7
    #   num: 1
    #   device: "cuda:0"
    # - hostname: pc8
    #   num: 1
    #   device: "cuda:0"

    # # 50*1.3=65
    # - hostname: pc1
    #   num: 9
    #   device: "cuda:0"
    # - hostname: pc2
    #   num: 5
    #   device: "cuda:0"
    # - hostname: pc3
    #   num: 8
    #   device: "cuda:0"
    # - hostname: pc4
    #   num: 8
    #   device: "cuda:0"
    # - hostname: pc5
    #   num: 8
    #   device: "cuda:0"
    # - hostname: pc6
    #   num: 9
    #   device: "cuda:0"
    # - hostname: pc7
    #   num: 9
    #   device: "cuda:0"
    # - hostname: pc8
    #   num: 9
    #   device: "cuda:0"
    
    - hostname: pc1
      num: 10
      device: "cuda:0"
    - hostname: pc2
      num: 5
      device: "cuda:0"
    - hostname: pc3
      num: 10
      device: "cuda:0"
    - hostname: pc4
      num: 10
      device: "cuda:0"
    - hostname: pc5
      num: 10
      device: "cuda:0"
    - hostname: pc7
      num: 10
      device: "cuda:0"
    - hostname: pc8
      num: 10
      device: "cuda:0"

# # 50
#   client:
#     - hostname: pc1
#       num: 9
#     - hostname: pc2
#       num: 2
#     - hostname: pc3
#       num: 7
#     - hostname: pc5
#       num: 7
#     - hostname: pc6
#       num: 7
#     - hostname: pc7
#       num: 9
#     - hostname: pc8
#       num: 9


# # 100
#   client:
#     - hostname: pc1
#       num: 23
#     - hostname: pc2
#       num: 8
#     - hostname: pc3
#       num: 23
#     - hostname: pc7
#       num: 23
#     - hostname: pc8
#       num: 23

# # 100
#   client:
#     - hostname: pc1
#       num: 18
#     - hostname: pc2
#       num: 8
#     - hostname: pc3
#       num: 18
#     - hostname: pc5
#       num: 18
#     - hostname: pc7
#       num: 19
#     - hostname: pc8
#       num: 19

# 6上面容易出现padding错误
# # 100
#   client:
#     - hostname: pc1
#       num: 18
#     - hostname: pc2
#       num: 8
#     - hostname: pc3
#       num: 18
#     - hostname: pc4
#       num: 18
#     - hostname: pc7
#       num: 19
#     - hostname: pc8
#       num: 19

  # client:
  #   - hostname: pc1
  #     num: 8
  #   - hostname: pc2
  #     num: 7
  #   - hostname: pc3
  #     num: 7
  #   - hostname: pc4
  #     num: 7
  #   - hostname: pc6
  #     num: 7
  #   - hostname: pc7
  #     num: 7
  #   - hostname: pc8
  #     num: 7


# # 200
#   client:
#     - hostname: pc1
#       num: 31
#     - hostname: pc2
#       num: 10
#     - hostname: pc3
#       num: 31
#     - hostname: pc4
#       num: 32
#     # - hostname: pc5
#     #   num: 20
#     - hostname: pc6
#       num: 32
#     - hostname: pc7
#       num: 32
#     - hostname: pc8
#       num: 32
      
# 150
  # client:
  #   - hostname: pc1
  #     num: 23
  #   - hostname: pc2
  #     num: 10
  #   - hostname: pc3
  #     num: 23
  #   - hostname: pc4
  #     num: 23
  #   # - hostname: pc5
  #   #   num: 20
  #   - hostname: pc6
  #     num: 23
  #   - hostname: pc7
  #     num: 24
  #   - hostname: pc8
  #     num: 24

  # client:
  #   - hostname: pc1
  #     num: 13
  #   - hostname: pc2
  #     num: 13
  #   - hostname: pc3
  #     num: 13
  #   - hostname: pc6
  #     num: 13
  #   - hostname: pc7
  #     num: 14
  #   - hostname: pc8
  #     num: 14
